root: "template_schema"
schemas:
  template_schema:
    type: "dict"
    props:
      pod_type:
        non_empty: true
        type: "str"
        choices: ["app", "web", "db"]
        description: "pod type"
      shared_network:
        type: "str"
        description: "shared network name"
      local:
        non_empty: true
        type: "bool"
        description: "pod in local host"
      main_dir:
        non_empty: true
        type: "str"
        description: "extension pod (this repository) directory"
      main_real_dir:
        non_empty: true
        type: "str"
        description: "extension pod (this repository) directory without links"
      inner_scripts_dir:
        type: "str"
        description: "directory inside containers to have the scripts (for running commands inside containers)"
      named_volumes:
        non_empty: true
        type: "bool"
        description: "specify to use named volumes instead of mapping the data in containers to host directories"
      internal:
        non_empty: true
        type: "bool"
        description: "specifies if the pod is internal in the host (no ports mapped to host ports)"
      use_secrets:
        non_empty: true
        type: "bool"
        description: "use secrets instead of environment variables for confidential data"
      use_fluentd:
        non_empty: true
        type: "bool"
        description: "when true, the services logging driver is fluentd"
      use_internal_fluentd:
        non_empty: true
        type: "bool"
        description: "when true, includes a fluentd service"
      use_secure_elasticsearch:
        non_empty: true
        type: "bool"
        description: "when true, uses authentication and tls to connect to elasticsearch"
      use_s3:
        non_empty: true
        type: "bool"
        description: "when true, includes a s3 client service"
      use_local_s3:
        non_empty: true
        type: "bool"
        description: >-
          when true, includes a local s3 server service to be used for
          backups and restores (mainly for development and tests)
      use_nginx:
        non_empty: true
        type: "bool"
        description: "when true, includes a nginx service to act as reverse proxy"
      use_grafana:
        non_empty: true
        type: "bool"
        description: "when true, includes a grafana service to act as gui for prometheus"
      use_theia:
        non_empty: true
        type: "bool"
        description: >-
          when true, includes a theia service to make easy to see the server logs and run
          predefined actions without the need of ssh-ing into the server
      use_minio_gateway:
        non_empty: true
        type: "bool"
        description: "when true, includes a minio gateway service to be used as a gui to access s3 buckets"
      use_custom_ssl:
        non_empty: true
        type: "bool"
        description: >-
          when true, uses custom ssl certificates (instead of certificates generated automatically
          by certbot)
      use_internal_ssl:
        non_empty: true
        type: "bool"
        description: >-
          when true, maps internal ssl certificates to some services so that they can access other,
          internal services, with self-signed certificates
      use_certbot:
        non_empty: true
        type: "bool"
        description: "when true, specifies that certbot is used to generate ssl certificates"
      use_node_exporter:
        non_empty: true
        type: "bool"
        description: >-
          when true, includes a node exporter service to export statistics about the host to
          the prometheus service (it's recommended to let this setting as false and instead
          run the node exporter service directly in the host, instead of in a container)
      use_cadvisor:
        non_empty: true
        type: "bool"
        description: "when true, includes a cadvisor service to collect statistics about the containers"
      fluentd_port:
        non_empty: true
        type: "str"
        description: "fluentd port (in localhost); defaults to 24224"
      fluentd_output_plugin:
        non_empty: true
        type: "str"
        choices: ["file", "elasticsearch"]
        description: "fluentd output plugin"
      elasticsearch_host:
        type: "str"
        description: "elasticsearch host (when fluentd_output_plugin=elasticsearch)"
      s3_cli:
        type: "str"
        choices: ["", "awscli", "mc", "rclone"]
        description: "s3 client type"

      grafana_port:
        non_empty: true
        type: "int"
        description: "grafana external port (in the host); defaults to 3000"
      grafana_server_domain:
        non_empty: true
        type: "str"
        description: "the grafana server domain (url used to access grafana)"
      grafana_smtp_enabled:
        non_empty: true
        type: "str"
        description: "enables smtp so that the grafana service can send emails"
      grafana_smtp_host:
        non_empty: true
        type: "str"
        description: "grafana smtp host with port (when grafana_smtp_enabled=true)"
      grafana_smtp_user:
        non_empty: true
        type: "str"
        description: "grafana smtp user (when grafana_smtp_enabled=true)"
      grafana_smtp_from_address:
        non_empty: true
        type: "str"
        description: "grafana smtp from address (when grafana_smtp_enabled=true)"
      prometheus_external_port:
        non_empty: true
        type: "str"
        description: "prometheus external port; defaults to 9090"
      ports:
        non_empty: true
        schema: "ports"
        description: "services external ports (in the host)"
      images:
        required: true
        type: "dict"
        description: "services container images"
      memory:
        required: true
        type: "dict"
        description: "services memory limits"
  ports:
    type: "dict"
    props:
      public_http_port:
        non_empty: true
        type: "int"
        description: "public http port; defaults to 80 in a remote host and to 8080 in a local host"
      public_https_port:
        non_empty: true
        type: "int"
        description: "public https port; defaults to 443 in a remote host and to 8443 in a local host"
      private_http_port:
        non_empty: true
        type: "int"
        description: "private http port; defaults to 9080"
      private_https_port:
        non_empty: true
        type: "int"
        description: "private https port; defaults to 9443"
