version: "2.4"

networks:
  internet:
    driver: "bridge"
  log:
    driver: "bridge"
  local:
    internal: true
    driver: "bridge"

x-logging:
  mainlog: &mainlog
    driver: "fluentd"
    options:
      tag: "docker.{{.Name}}.{{.ID}}"
      fluentd-address: "localhost:$FLUENTD_PORT"
  jsonlog: &jsonlog
    driver: "json-file"
    options:
      max-size: "50m"

services:
  toolbox:
    container_name: "${CTX_PREFIX_MAIN}toolbox"
    hostname: "toolbox"
    build:
      context: .
      dockerfile: "main/toolbox/Dockerfile"
      args:
        IMAGE: $TOOLBOX_IMAGE
        VERSION: $TOOLBOX_VERSION
    restart: "unless-stopped"
    depends_on:
      - "fluentd"
    networks:
      - "internet"
      - "local"
    volumes:
      - "$DATA_DIR:/var/main/data"
      - "$DATA_DIR/tmp:/tmp/main"
      - "$DATA_DIR/log:/var/log/main"
    logging: *mainlog
    command: "tail -f /dev/null"
    mem_limit: $CONTAINER_MEM_TOOLBOX

  fluentd:
    container_name: "${CTX_PREFIX_MAIN}fluentd"
    hostname: "fluentd"
    build:
      context: .
      dockerfile: "main/fluentd/Dockerfile"
      args:
        IMAGE: $FLUENTD_IMAGE
        VERSION: $FLUENTD_VERSION
    restart: "unless-stopped"
    ports:
      - "$FLUENTD_PORT:24224"
      - "$FLUENTD_PORT:24224/udp"
    networks:
      - "log"
    volumes:
      - "$DATA_DIR/log/fluentd:/var/log/main/fluentd/"
    logging: *jsonlog
    mem_limit: $CONTAINER_MEM_FLUENTD
