# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: Prometheus
    # <string, required> datasource type. Required
    type: prometheus
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    url: "{{ params.prometheus_url }}"
    # <string> database password, if used
    password: "{{ params.prometheus_password | default('') }}"
    # <string> database user, if used
    user: "{{ params.prometheus_user | default('') }}"
    # <string> database name, if used
    database: "{{ params.prometheus_database | default('') }}"
    # <bool> enable/disable basic auth
    basicAuth: "{{ params.prometheus_basic_auth | default(false) | lower }}"
    # <string> basic auth username, if used
    basicAuthUser: "{{ params.prometheus_basic_auth_user | default('') }}"
    # <string> basic auth password, if used
    basicAuthPassword: "{{ params.prometheus_basic_auth_password | default('') }}"
    # <bool> enable/disable with credentials headers
    withCredentials:
    # <bool> mark as default datasource. Max one per org
    isDefault: true
    version: 1
