root: "template_schema"
schemas:
  template_schema:
    type: "dict"
    props:
      ctx_full_name:
        non_empty: true
        type: "str"
        description: "context full name / project name (used as a namespace for docker-compose)"
      ctx_prefix_main:
        type: "str"
        required: true
        description: "prefix for the services in the main docker-compose file (permanent services)"
      ctx_prefix_run:
        type: "str"
        required: true
        description: "prefix for the services in the secondary docker-compose file (transient services)"
      type:
        type: "str"
        non_empty: true
        choices: ["app", "web", "db"]
        description: "pod type"
      local:
        type: "bool"
        non_empty: true
        description: "pod in local host"
      data_dir:
        type: "str"
        non_empty: true
        description: "data directory path (when local=true, the path is relative to the pod directory)"
      use_bot:
        non_empty: true
        type: "bool"
        description: "when true, includes a hubot service that is able to access rocketchat"
      use_secrets:
        type: "bool"
        non_empty: true
        description: "use secrets instead of environment variables for confidential data"
      use_minio_gateway:
        type: "bool"
        non_empty: true
        description: "specifies that the minio gateway service is being used"
      use_local_s3:
        type: "bool"
        non_empty: true
        description: "specifies that a local s3 service is being used"
      minio_gateway_endpoint:
        type: "str"
        description: "minio gateway endpoint (when use_minio_gateway=true)"
      minio_gateway_access_key:
        type: "str"
        description: "minio gateway access key (when use_minio_gateway=true)"
      minio_gateway_secret_key:
        type: "str"
        description: "minio gateway secret key (when use_minio_gateway=true)"
      local_s3_access_key:
        type: "str"
        description: "local s3 access key (when use_local_s3=true)"
      local_s3_secret_key:
        type: "str"
        description: "local s3 secret key (when use_local_s3=true)"
      rocketchat_fileupload_storage_type:
        type: "str"
        choices: ["FileSystem", "AmazonS3"]
        description: "rocketchat fileupload storage type"
      rocketchat_fileupload_s3_access_key:
        type: "str"
        description: "rocketchat fileupload s3 access key"
      rocketchat_fileupload_s3_secret_key:
        type: "str"
        description: "rocketchat fileupload s3 secret key"
      rocketchat_enable_smtp:
        type: "str"
        description: >-
          uses an external (third party) email service to send rocketchat emails (recommended)
      rocketchat_smtp_password:
        type: "str"
        description: "rocketchat smtp password"
      db_password:
        type: "str"
        description: "database user password"
      db_oplog_password:
        type: "str"
        description: "database oplog user password"
      db_root_pass:
        type: "str"
        description: "database root user (superuser) pass"
      hubot_password:
        type: "str"
        description: "hubot password"
      db_gui_password:
        type: "str"
        description: "database gui user password"
